#!/bin/bash

cmake -DCMAKE_INSTALL_PREFIX="$HOME/install/sundials-6.2" \
	-DCMAKE_BUILD_TYPE="Debug" \
	-DCMAKE_C_COMPILER="gcc" \
	-DCMAKE_CXX_COMPILER="g++" \
	-DCMAKE_Fortran_COMPILER="gfortran" \
	-DENABLE_CUDA="ON" \
	-DCUDA_TOOLKIT_ROOT_DIR="/usr/local/cuda" \
	-DEXAMPLES_ENABLE_C="ON" \
	-DEXAMPLES_ENABLE_CXX="ON" \
	-DEXAMPLES_ENABLE_CUDA="ON" \
	-DENABLE_LAPACK="ON" \
	-DENABLE_MAGMA="ON" \
	-DMAGMA_DIR="$HOME/install/magma" \
	-DSUNDIALS_INDEX_SIZE="32" \
	-DENABLE_OPENMP="ON" \
	-DENABLE_PTHREAD="ON" \
	-DSUNDIALS_BUILD_WITH_PROFILING="ON" \
	-DSUNDIALS_LOGGING_LEVEL="4" \
	../
